version: "3.7"
services:
  traefik:
    image: "traefik"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./acme.json:/acme.json"
      - "./traefik.toml:/traefik.toml"
      - "./traefik_dynamic.toml:/traefik_dynamic.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    restart: always
    volumes:
      - "mariadb_data:/bitnami/mariadb"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_PASSWORD=statwig
      - MARIADB_DATABASE=bitnami_redmine
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.rule=Host(`redmine.statledger.io`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=lets-encrypt"

  redmine:
    image: docker.io/bitnami/redmine:5
    ports:
      - "80:3000"
    volumes:
      - "redmine_data:/bitnami/redmine"
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=bn_redmine
      - REDMINE_DATABASE_PASSWORD=statwig
      - REDMINE_DATABASE_NAME=bitnami_redmine

volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local

networks:
  default:
    external:
      name: proxy
