version: "3.7"
services:
  traefik:
    image: "traefik"
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./acme.json:/acme.json"
      - "./traefik.toml:/traefik.toml"
      - "./dynamic.toml:/dynamic.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  mariadb:
    image: mariadb
    container_name: database
    restart: always
    volumes:
      - "./mariadb_data:/mariadb"
    environment:
      - MARIADB_ROOT_PASSWORD=statwig
      - MARIADB_USER=user_redmine
      - MARIADB_PASSWORD=statwig2022
      - MARIADB_DATABASE=statwig_redmine

  redmine:
    image: redmine:5.0.1
    container_name: redmine
    ports:
      - "3000:3000"
    volumes:
      - "./redmine_data:/redmine"
      - "./configuration.yml:/usr/src/redmine/config/configuration.yml'"
    depends_on:
      - mariadb
    environment:
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=user_redmine
      - REDMINE_DATABASE_PASSWORD=statwig2022
      - REDMINE_DATABASE_NAME=statwig_redmine
      - REDMINE_SMTP_HOST=smtp.gmail.com
      - REDMINE_SMTP_PORT=587
      - REDMINE_SMTP_USER=dev@statwig.com
      - REDMINE_SMTP_PASSWORD=StaTwig@123
      - REDMINE_SMTP_SECURE=false
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.rule=Host(`redmine.statledger.io`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=lets-encrypt"

volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local

networks:
  default:
    name: proxy
    external: true
